CREATE DATABASE laboratorio;
USE DATABASE laboratorio;


DROP TABLE IF EXISTS userlab;
CREATE TABLE userlab (
    id INT(5) NOT NULL  PRIMARY KEY AUTO_INCREMENT,
    usuario VARCHAR(50) NOT NULL UNIQUE,
    contraseña VARCHAR(50) NOT NULL,
    correo VARCHAR(50) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS datalab;
CREATE TABLE datalab (
    id INT(5) NOT NULL  PRIMARY KEY AUTO_INCREMENT
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;